### PR TITLE
Add linq support for `Select`, `Where`, `OnConflict`, `Columns`, `Order`, `Update`, `Set`, and `Delete`

### PR DESCRIPTION
**Pull request by acupofjose**
In reference to #58 

- [x] Linq usage of `Select(x => new[] { x.Name, x.CreatedAt })`
- [x] Linq usage of `Where(x => x.Id == 5)`
- [x] Linq  usage of `Where(x => x.Name == "Top Gun" && x.CreatedAt <= new DateTime(2022, 08, 21))`
   - [x] Support usage of `Contains` operator:
       - [x] `String.Contains`
       - [x] `ICollection.Contains`
- [x] Support for chaining `Where` calls.
- [x] Linq for `OnConflict`
- [x] Linq for `Columns`
- [x] Linq for `Order`
- [x] Linq for `Filter` 
- [x] Linq for `Update` and `Set`
- [x] Linq for `Delete`
- [x] Unit tests
- [x] Update README

### CODE REVIEW

**Comment by acupofjose** [comment]
@veleek any chance you'd be up for some more code review? I'd love your opinion on this!

**Comment by veleek** [comment]
Shoot, looks like I got to this too late. :)

**Comment by veleek** [comment]
Took a quick glance through and didn't see anything immediately troubling.   But I'm not super familiar with expressions either.

**Comment by acupofjose** [comment]
Lol that’s what I get for coding on the weekend. Appreciate your time as always! Thanks @veleek

**Pull request merged**
