### PR TITLE
Added cancellation token support

### PR DESCRIPTION
**Pull request by devpikachu**
Added CancellationToken support as noted in #46

### CODE REVIEW

**Comment by acupofjose** [comment]
Great idea! Thank you for this. Code looks good to me, but could you add a test method to try against? If not, I can merge and add a case before the version bump this afternoon or tomorrow

**Comment by devpikachu** [comment]
> Great idea! Thank you for this. Code looks good to me, but could you add a test method to try against? If not, I can merge and add a case before the version bump this afternoon or tomorrow

Sure thing! I'll add a test method and update the PR once done. 😄

**Comment by devpikachu** [comment]
@acupofjose I've added the mentioned test case for cancellation tokens. Do note that I've given the token source as low of TimeSpan as possible (1 tick), however, this still might be too slow in certain edge-cases, triggering a false-failed test.

If you know of a better way to reliably test cancellation tokens, please do let me know.

**Comment by acupofjose** [comment]
This is perfect, thanks for doing this so efficiently. That seems to be the best way I know of to test cancellation tokens! - I'll get put it (with credit) in the next release.

Implements #46

**Pull request merged**
