### PR TITLE
minor refactors and clean ups

### PR DESCRIPTION
**Pull request by kolosovpetro**
I have performed minor refactors and clean ups so that code became less "noisy" :)

### CODE REVIEW

**Comment by acupofjose** [comment]
Wow - you really went through it all - thank you so much! That was not a trivial scan through the codebase. I just had a question about that variable change, otherwise everything else looks great to me. It was in need of a cleanup!

**Comment by kolosovpetro** [comment]
> I just had a question about that variable change

Hi, thanks for the review. What variable exactly?

**Comment by acupofjose** [comment]
The `NULL_VAL` variable in QueryFilter.cs

**Comment by kolosovpetro** [comment]
> The `NULL_VAL` variable in QueryFilter.cs

According to Microsoft's Framework Design Guidelines `const` values should be named in PascalCase,

Please refer to the following stackoverflow discussion in order to see other details: https://stackoverflow.com/a/242549

**Pull request merged**
