### PR TITLE
Fixing zero length content when sending requests without body

### PR DESCRIPTION
**Pull request by SameerOmar**
This fixes an issue when calling the Count function on a table/view

### CODE REVIEW

**Comment by acupofjose** [comment]
@SameerOmar thanks for opening a PR! Unfortunately these changes cause some issues with several of the test's expected outputs. Could you look into those before we go about merging?

**Comment by SameerOmar** [comment]
@acupofjose could you rerun the tests

**Comment by SameerOmar** [comment]
@acupofjose tests fulfilled now

**Comment by acupofjose** [comment]
Wonderful, thanks again!

**Pull request merged**
